Add files via upload
Cheburajka/7th-semester pull request #1
Opened 2023-09-22 06:59 UTC by Cheburajka

task 1

2023-09-22 07:40 UTC, MarinaPaley requested changes

2023-09-22 07:40 UTC, MarinaPaley commented on main.cpp
> +    const uniform_int_distribution<int> uniformIntDistribution(min, max);
`const` просто уберите

2023-09-22 07:40 UTC, MarinaPaley commented on main.cpp
> +void fillArrayRandom(int* arr, int size, int min, int max)
`const`, `size_t`.
Вся реализация после `main()`

2023-09-22 07:40 UTC, MarinaPaley commented on main.cpp
> +@ ������� ��� ���������� ������� ���������� �������
`UTF-8`
https://developer.lsst.io/cpp/api-docs.html#documentation-must-use-javadoc-style-tags

2023-09-22 07:40 UTC, MarinaPaley commented on main.cpp
> +    }
убрать

2023-09-22 07:40 UTC, MarinaPaley commented on main.cpp
> +
убрать

2023-09-22 07:40 UTC, MarinaPaley commented on main.cpp
> +    // ���� ������������ � ������������� �������� ��� ��������� ��������� �����
Для индексации массивов и работы с их размерностью лучше использовать тип [`size_t`](https://en.cppreference.com/w/cpp/types/size_t). Для проверки корректности значения, которое будет использовано в качестве размера массива, нужно использовать тип [`int`](https://en.cppreference.com/w/cpp/language/types#Signed_and_unsigned_integer_types), например, следующим образом:

```cpp
size_t get_size(const std::string& message)
{
    int size = -1;
    std::cout << message;
    std::cin >> size;

    if (size < 0)
    {
        throw std::out_of_range("Incorrect size. Value has to be greater or equal zero.");
    }

    return size;
}
```

2023-09-22 07:40 UTC, MarinaPaley commented on main.cpp
> +    delete[] arr;
Массив необходимо удалять следующим безопасным способом
```cpp
if (array != nullptr)
{
   delete[] array;
   array = nullptr;
}
```

2023-10-11 18:52 UTC, closed without merging

2023-10-11 18:56 UTC, Cheburajka commented
Исправлен

2023-10-11 18:58 UTC, Cheburajka commented
Исправления